site_name: KOBConnect
theme:
  name: material
nav:
  - Overview: index.md
  - Dependent Projects: dependent.md
  - Motivation: motivation.md
  - Status of the project: status.md
  - Solution: solution.md
  - Contributors: contributor.md
  - License: license.md
  - References: reference.md